"use strict";

let ChainTypes;

module.exports = ChainTypes = {};

ChainTypes.reserved_spaces = {
  relative_protocol_ids: 0,
  protocol_ids: 1,
  implementation_ids: 2
};

ChainTypes.operations = {
  vote: 0,
  content: 1,
  transfer: 2,
  transfer_to_vesting: 3,
  withdraw_vesting: 4,
  account_update: 5,
  validator_update: 6,
  account_validator_vote: 7,
  account_validator_proxy: 8,
  delete_content: 9,
  custom: 10,
  set_withdraw_vesting_route: 11,
  request_account_recovery: 12,
  recover_account: 13,
  change_recovery_account: 14,
  escrow_transfer: 15,
  escrow_dispute: 16,
  escrow_release: 17,
  escrow_approve: 18,
  delegate_vesting_shares: 19,
  account_create: 20,
  account_metadata: 21,
  proposal_create: 22,
  proposal_update: 23,
  proposal_delete: 24,
  chain_properties_update: 25,
  author_reward: 26,
  curation_reward: 27,
  content_reward: 28,
  fill_vesting_withdraw: 29,
  shutdown_validator: 30,
  hardfork: 31,
  content_payout_update: 32,
  content_benefactor_reward: 33,
  return_vesting_delegation: 34,
  committee_worker_create_request: 35,
  committee_worker_cancel_request: 36,
  committee_vote_request: 37,
  committee_cancel_request: 38,
  committee_approve_request: 39,
  committee_payout_request: 40,
  committee_pay_request: 41,
  validator_reward: 42,
  create_invite: 43,
  claim_invite_balance: 44,
  invite_registration: 45,
  versioned_chain_properties_update: 46,
  award: 47,
  receive_award: 48,
  benefactor_award: 49,
  set_paid_subscription: 50,
  paid_subscribe: 51,
  paid_subscription_action: 52,
  cancel_paid_subscription: 53,
  set_account_price: 54,
  set_subaccount_price: 55,
  buy_account: 56,
  account_sale: 57,
  use_invite_balance: 58,
  expire_escrow_ratification: 59,
  fixed_award: 60,
  target_account_sale: 61,
  bid: 62,
  outbid: 63,
  set_reward_sharing: 64,
  stakeholder_reward: 65,
  // Prediction Markets (HF14) — user operations
  pm_oracle_register: 66,
  pm_oracle_update: 67,
  pm_create_market: 68,
  pm_oracle_accept_market: 69,
  pm_place_bet: 70,
  pm_commit_bet: 71,
  pm_reveal_bet: 72,
  pm_cancel_bet: 73,
  pm_add_liquidity: 74,
  pm_withdraw_liquidity: 75,
  pm_resolve_market: 76,
  pm_no_contest: 77,
  pm_dispute_create: 78,
  pm_dispute_vote: 79,
  pm_dispute_resolve: 80,
  pm_transfer_position: 81,
  pm_lazy_deposit: 82,
  pm_lazy_withdraw: 83,
  // Prediction Markets (HF14) — virtual operations
  pm_batch_settle: 84,
  pm_commit_forfeit: 85,
  pm_auto_payout: 86,
  pm_dispute_finalize: 87,
  pm_dispute_auto_close: 88,
  pm_oracle_missed_penalty: 89,
  pm_lazy_recall: 90,
  // Prediction Markets (HF14) — leverage user operations
  pm_leverage_open: 91,
  pm_leverage_close: 92,
  pm_leverage_convert: 93,
  // Prediction Markets (HF14) — leverage/accept virtual operations
  pm_leverage_liquidate: 94,
  pm_leverage_resolve: 95,
  pm_market_accepted: 96,
  pm_payout: 97,
  // Prediction Markets (HF14) — dispute/ban user operations
  pm_dispute_oracle_respond: 98,
  pm_unban: 99,
  // Prediction Markets (HF14) — ban expiry virtual operation
  pm_ban_expired: 100,
  // Prediction Markets (HF14) — oracle-accept-window expiry virtual operation
  pm_market_expired: 101,
  // Aliases for backward compatibility (old witness names)
  witness_update: 6,
  account_witness_vote: 7,
  account_witness_proxy: 8,
  shutdown_witness: 30,
  witness_reward: 42
};

//types.hpp
ChainTypes.object_type = {
  "null": 0,
  base: 1
};